### ISSUE TITLE
Question about the extension

### ISSUE THREAD

**Issue by Karl456** [rakeshmagento/magento2-shipping-per-product#2]
Does this extension take the highest price of shipping and use that, or does it add all of the prices to create a final total?

e.g.

Product 1 - £10
Product 2 - £15

I want the total to be £15 (the highest value), instead of £25 (the total).

**Comment by rakeshmagento** [comment]
It will add all the product prices, for your requirement it needs to be
customized...:)


Rakesh Jakhar
*Director, Sr. Magento Developer*
E-commerce
Octonism Infotech Pvt. Ltd.
m: +91-94143-49999
a: B 27 Lal Bhadur Nagar, Malviya Nagar, Jaipur
e: rakesh.jakhar1986@gmail.com
<https://www.facebook.com/rakesh.jakhar1987>
<https://www.linkedin.com/in/rakesh-jakhar-49b84b54/>

Magento Certified Developer
<https://www.magentocommerce.com/certification/directory/dev/160417/>
